### ISSUE TITLE
500 Internal Error caused when using route.id=Logan-xx on MBTA

### ISSUE THREAD

**Issue by Cybermite** [spaceboats/busbus#25]
URL: http://ec2-54-68-11-133.us-west-2.compute.amazonaws.com/arrivals?start_time=1430513972&end_time=1430514872&route.id=Logan-22&provider.id=a1e7223b0b10c3025456e11c1b63243dc9630398&_expand=routes%2Cstops%2C

Traceback: 
Traceback (most recent call last):
  File "/home/ec2-user/venv/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/ec2-user/venv/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/ec2-user/busbus/busbus/web.py", line 14, in json_handler
    return BaseEntityJSONEncoder().encode(value).encode('utf-8')
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/ec2-user/busbus/busbus/entity.py", line 79, in default
    return list(o)
  File "/home/ec2-user/busbus/busbus/web.py", line 28, in <genexpr>
    return ({attr: unexpand(value, to_expand)
  File "/home/ec2-user/busbus/busbus/util/__init__.py", line 25, in next
    return self.__next__()
  File "/home/ec2-user/busbus/busbus/queryable.py", line 58, in __next__
    return next(self.it)
  File "/home/ec2-user/busbus/busbus/util/__init__.py", line 25, in next
    return self.__next__()
  File "/home/ec2-user/busbus/busbus/queryable.py", line 30, in __next__
    value = next(self.it)
  File "/usr/lib64/python2.7/heapq.py", line 376, in merge
    h_append([next(), itnum, next])
  File "/home/ec2-user/busbus/busbus/util/__init__.py", line 25, in next
    return self.__next__()
  File "/home/ec2-user/busbus/busbus/util/arrivals.py", line 53, in __next__
    self.it = self._build_iterable()
  File "/home/ec2-user/busbus/busbus/provider/mbta.py", line 83, in _build_iterable
    its = list(six.moves.map(yield_predictions_by_route, self.routes))
  File "/home/ec2-user/busbus/busbus/provider/mbta.py", line 67, in yield_predictions_by_route
    for dir in resp.json()['direction']:
KeyError: 'direction'

**Comment by ianweller** [comment]
Fixed in some varying number of commits in #26
